org: thibaultmaekelbergh
app: 'vrt-api-service'
service: 'vrt-radio-api-mapper'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: ${file(../sls.global.yml):aws_nodejs_runtime}
  region: ${file(../sls.global.yml):aws_region}

functions:
  vrt_api_mapper:
    handler: index.handler
    events:
      - http:
          method: get
          cors: true
          path: '/{channelName}'
          request:
            parameters:
              paths:
                channelName: true
