service:
  name: ivago-waste-collection

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getWasteCollection:
    handler: index.handler
    events:
      - http:
          method: get
          path: /{calendar}
          request:
            parameters:
              paths:
                calendar: true
