org: thibaultmaekelbergh
app: 'ivago-waste-collection'
service: 'ivago-waste-collection'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: ${file(../sls.global.yml):aws_nodejs_runtime}
  region: ${file(../sls.global.yml):aws_region}

functions:
  getWasteCollection:
    handler: index.handler
    events:
      - http:
          method: get
          path: '/{calendar}'
          request:
            parameters:
              paths:
                calendar: true
