org: thibaultmaekelbergh
app: 'contentful-services'
service: 'contentful-services'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: ${file(../sls.global.yml):aws_nodejs_runtime}
  region: ${file(../sls.global.yml):aws_region}
  environment:
    BUCKET_NAME: ${file(./env.json):BUCKET_NAME}
    MANAGEMENT_TOKEN: ${file(./env.json):MANAGEMENT_TOKEN}
    SPACE_ID: ${file(./env.json):SPACE_ID}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource:
            - 'arn:aws:s3:::${self:service}/*'

functions:
  backupSpace:
    handler: spaceBackup.handler
    environment:
      BUCKET_NAME: ${self:service}
    events:
      - schedule: rate(12 hours)
