org: thibaultmaekelbergh
app: 'discogs-services'
service: 'discogs-random-record'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: ${file(../sls.global.yml):aws_nodejs_runtime}
  region: ${file(../sls.global.yml):aws_region}
  environment:
    DISCOGS_API_TOKEN: ${file(./env.json):DISCOGS_API_TOKEN}

functions:
  getRandomRecord:
    handler: index.getRandomRecord
    events:
      - http:
          method: get
          path: /
